name: run-tests-actions
on: [push, pull_request]
jobs:
  unittests-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Tests
      run: |
        python -m unittest discover -v -s "tests" -p "*_test.py" -t "."
    - name: Coverage
      run: |
        coverage run -m unittest discover -s "tests" -p "*_test.py" -t "."
        coverage report
